field: f7961df6-d96e-4b26-bb02-f65641c036e1 # Additional Logos
fieldLayouts:
  578a9e90-4e50-42fb-9adc-d757c8eac929:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e5d98e50-304d-4dca-8fa0-be1431d687a7 # Logo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 85c80ce1-e6eb-4082-94cf-07809fcd66b3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d5203bad-2433-4750-a65d-c36258d5f4fe # Logo Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c9d766ff-1c04-47ca-8871-1bc6e521a490
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d247e945-d9dc-48ce-9f16-04c23643816f
        userCondition: null
fields:
  d5203bad-2433-4750-a65d-c36258d5f4fe: # Logo Text
    columnSuffix: pbhutsze
    contentColumnType: text
    fieldGroup: null
    handle: logoText
    instructions: null
    name: 'Logo Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e5d98e50-304d-4dca-8fa0-be1431d687a7: # Logo
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: logo
    instructions: null
    name: Logo
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:35279a43-bca0-475d-a8da-25e0ecbccac7' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:35279a43-bca0-475d-a8da-25e0ecbccac7' # Images
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: logos
name: Logos
sortOrder: 1
