fieldLayouts:
  8fa9a8aa-d7ef-476b-bbf8-2f7f0e8da48a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 701709a5-a9a5-4bf8-bbf3-178ae810715e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0aa7bf8b-d4e1-4016-bc62-588296598ca8 # Blocks
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f61fc1ef-7590-4256-b75d-ae690f7353b2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8166f6e2-7f84-40b6-86ce-f3567d52685f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4a6ccf0d-3c6f-4845-8311-f049b4c1a304 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fbb72529-35dd-4aa1-9915-7c51c8c30b45
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: fdeaf8df-0f56-45a6-a26d-a2c2aafae16e
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 44339fe6-1c99-46f8-875d-9fbd1bcf5719 # Pages
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
