childBlocks: null
conditions: null
description: ''
enabled: true
field: f904b728-951f-4cbd-bb1a-984f00b2d9ea # Longform
fieldLayouts:
  72ad9ea9-640a-486a-87dc-3ef3a096ea59:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 677709f9-0b6b-4d19-969c-0495c252dcca # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 248b363c-85a6-46f6-9d08-22cff879969d
            userCondition: null
            warning: null
            width: 100
        name: Image
        uid: b3a891b1-2ca4-477e-9ff2-0bfbbd209165
        userCondition: null
group: null
groupChildBlockTypes: true
handle: image
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Image
topLevel: true
