childBlocks:
  - pillar
conditions: null
description: ''
enabled: true
field: 0aa7bf8b-d4e1-4016-bc62-588296598ca8 # Blocks
fieldLayouts:
  076ef3c2-713b-4fef-b74e-9e21bf00153c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f98c72b8-c1fd-47d1-b532-93b73afdfef1 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 42613cd3-65f4-43dc-a551-aae52d2d5628
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: benf\neo\fieldlayoutelements\ChildBlocksUiElement
            uid: 29637f6a-ee72-4a99-ae22-b515a9abfb17
            userCondition: null
        name: Content
        uid: da5a4137-db15-434b-994a-23756542c6ec
        userCondition: null
group: null
groupChildBlockTypes: true
handle: pyramid
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 1
minSiblingBlocks: 0
name: Pyramid
topLevel: true
