columnSuffix: fklfearz
contentColumnType: text
fieldGroup: 98247db1-d35e-4bd4-83a2-d402d919b73b # Globals
handle: address
instructions: null
name: Address
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
