columnSuffix: lzgnplmz
contentColumnType: text
handle: bodySimple
instructions: null
name: 'Body Simple'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: ''
  columnType: text
  css: null
  cssFile: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  fullGraphqlData: false
  headingLevels: false
  js: null
  jsFile: null
  options: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  toolbar:
    - bold
    - italic
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
