columnSuffix: cgfjklrm
contentColumnType: string
fieldGroup: 98247db1-d35e-4bd4-83a2-d402d919b73b # Globals
handle: email
instructions: null
name: Email
searchable: false
settings:
  placeholder: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
