columnSuffix: null
contentColumnType: string
fieldGroup: 8f2cdb70-2597-45f1-8c20-f1d1b471e1f6 # Common
handle: sectors
instructions: null
name: Sectors
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  sources:
    - 'section:c5253114-01ce-4026-a1b8-93d94021a482' # Sectors
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
