columnSuffix: hrdzyenm
contentColumnType: text
fieldGroup: 8f2cdb70-2597-45f1-8c20-f1d1b471e1f6 # Common
handle: subheading
instructions: null
name: Subheading
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
